Completed Issue 3 User can edit an entry - Bryan Brown
bbrown949/code-journal pull request #7
Opened 2023-04-21 18:34 UTC by bbrown949

[ezgif.com-optimize.gif.zip](https://github.com/bbrown949/code-journal/files/11298405/ezgif.com-optimize.gif.zip)

2023-04-21 21:27 UTC, shawnkost requested changes
Looking good so far! Just a few changes here Bryan!

2023-04-21 21:27 UTC, shawnkost commented on index.html
> +              <div class="notes-label"><label for="notes-id">Notes</label></div>
The `for` attribute should just be `notes`. It needs to match whatever the `id` value is

2023-04-21 21:27 UTC, shawnkost commented on js/main.js
> +// const $entryForm = document.querySelector('form');
Delete all old code!

2023-04-21 21:27 UTC, shawnkost commented on js/main.js
> +    // const $renderEntry = renderEntry(singleData);
Delete all old code

2023-04-21 21:27 UTC, shawnkost commented on js/main.js
> +  // $entryForm.reset();
Delete all old code

2023-04-21 21:27 UTC, shawnkost commented on js/main.js
> +    data.editing.url = event.target.elements.url.value;
`data.editing` already has these values, so you shouldn't be updating `data.editing`, you want to be updating `data.entries`. So you'll need to find the current entry that exists in `data.entries` and replace it with these newly edited values

2023-04-22 00:08 UTC, bbrown949 commented
updated

2023-04-22 01:09 UTC, shawnkost approved these changes
👍🏻

2023-04-22 13:41 UTC, merged